'use client'

import React, { useState } from 'react'
import Navbar from '@/app/components/navbar'
import Categorias from '@/app/components/categorias/categorias'
import './styles.css'
import { Divider } from '@mui/material'
import Productos from '@/app/components/productos/productos'
function ListaProductos() {
  return (
    <>
      <head>
        <title>Lista de Productos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </head>
      <body>
        <Navbar />

        <div style={{ alignItems: 'center', marginRight: '5%', marginLeft: '5%', marginTop: '2%' }}>

          <div style={{ color: '#090069', marginBottom: '1%' }}>
            <h1>Lista de productos</h1>
          </div>

          <Divider />
          <div style={{display: 'flex'}}>
            <Categorias />
            <Divider orientation='vertical'  flexItem />
            <Productos />
          </div>
        </div>


      </body>
    </>
  )
}

export default ListaProductos