'use client'
import Navbar from '@/app/components/navbar'
import React from 'react'
import { styled } from '@mui/material/styles';
import './styles.css'
import { Box, Button, Divider } from '@mui/material'
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Unstable_Grid2';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TablePagination from '@mui/material/TablePagination';
import TableSortLabel from '@mui/material/TableSortLabel';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import postobon from '../../../../public/images/postobon.webp'
import Image from 'next/image';
import ShoppingBagOutlinedIcon from '@mui/icons-material/ShoppingBagOutlined';
import LocalPrintshopOutlinedIcon from '@mui/icons-material/LocalPrintshopOutlined';
import DeleteOutlinedIcon from '@mui/icons-material/DeleteOutlined';
import CancelOutlinedIcon from '@mui/icons-material/CancelOutlined';
import ModeEditOutlineOutlinedIcon from '@mui/icons-material/ModeEditOutlineOutlined';
import { useRouter } from 'next/navigation'

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
  ...theme.typography.body2,
  padding: theme.spacing(1),
  margin: theme.spacing(2),
}));


const cliente = [
  {
    id: 1,
    nombre: 'Carlos',
    apellido: 'Perez',
    email: 'carlos.perez@gmail.com',
    telefono: '1234567890',
    direccion: 'Calle 123',
  }
]

const orden = [
  {
    id: 1,
    fecha: '16 de Mayo de 2025',
    vendedor: 'Sarah Paulson',
    estado: 'En proceso',
  }
]

const productos = [
  {
    id: 1,
    imagen: postobon,
    nombre: 'Producto 1',
    referencia: '123456',
    cantidad: 2,
    precio: 100,
  },
  {
    id: 2,
    imagen: postobon,
    nombre: 'Producto 2',
    referencia: '123456',
    cantidad: 3,
    precio: 100,
  },
  {
    id: 2,
    imagen: postobon,
    nombre: 'Producto 2',
    referencia: '123456',
    cantidad: 3,
    precio: 100,
  },
  {
    id: 2,
    imagen: postobon,
    nombre: 'Producto 2',
    referencia: '123456',
    cantidad: 3,
    precio: 100,
  },
  {
    id: 2,
    imagen: postobon,
    nombre: 'Producto 2',
    referencia: '123456',
    cantidad: 3,
    precio: 100,
  }
]

function Pedido() {
  const router = useRouter()
  const handleEdit = () => {
    router.push('/pages/pedido/editar?id=1')
  }
  return (
    <>
      <head>
        <title>Pedido</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </head>
      <body>
        <header>
          <Navbar />
        </header>
        <main>
          <Box className='contenedor'>
            <Box className='top-bar'>
              <Grid container>
                <Grid xs={6} spacing={2} sx={{ display: 'flex', alignItems: 'center' }}>
                  <ShoppingBagOutlinedIcon sx={{ marginRight: '1%', color: '#090069' }} />
                  <p style={{ fontSize: '1.3em', color: '#090069' }}>Detalles de la orden</p>
                </Grid>
                <Grid xs={6}>
                  <Grid container spacing={2} sx={{ display: 'flex', justifyContent: 'flex-end' }}>
                    <Grid>
                      <Button variant="outlined" className='imprimir' sx={{ textTransform: 'none' }} startIcon={<LocalPrintshopOutlinedIcon />}>Imprimir</Button>
                    </Grid>
                    <Grid>
                      <Button variant="outlined" className='imprimir' sx={{ textTransform: 'none' }} startIcon={<ModeEditOutlineOutlinedIcon />} onClick={handleEdit}>Editar pedido</Button>
                    </Grid>
                    <Grid>
                      <Button variant="outlined" color='error' sx={{ textTransform: 'none' }} startIcon={<CancelOutlinedIcon />}>Cancelar orden</Button>
                    </Grid>
                  </Grid>
                </Grid>
              </Grid>
            </Box>
            <Grid className='elementos' container spacing={1} columns={2}>
              <Grid xs={6} md={1}>
                <Item>
                  <h2>Detalles del cliente</h2>
                  <Divider />
                  {cliente.map(({ id, nombre, apellido, email, telefono, direccion }) => {
                    return (
                      <div key={id} className='detalles'>
                        <div>
                          <p className='subtitulo'>Nombre</p>
                          <p>{nombre} {apellido}</p>
                        </div>
                        <div>
                          <p className='subtitulo'>Email</p>
                          <p>{email}</p>
                        </div>
                        <div>
                          <p className='subtitulo'>Telefono</p>
                          <p>{telefono}</p>
                        </div>
                        <div>
                          <p className='subtitulo'>Direccion</p>
                          <p>{direccion}</p>
                        </div>
                      </div>
                    )
                  })}
                </Item>
              </Grid>
              <Grid xs={6} md={1}>
                <Item>
                  <h2>Detalles del pedido</h2>
                  <Divider />
                  {orden.map(({ id, fecha, vendedor, estado }) => {
                    return (
                      <div key={id} className='detalles'>
                        <div>
                          <p className='subtitulo'>Pedido No.</p>
                          <p>{id}</p>
                        </div>
                        <div>
                          <p className='subtitulo'>Fecha</p>
                          <p>{fecha}</p>
                        </div>
                        <div>
                          <p className='subtitulo'>Vendedor</p>
                          <p>{vendedor}</p>
                        </div>
                        <div>
                          <p className='subtitulo'>Estado</p>
                          <p><b>{estado}</b></p>
                        </div>
                      </div>
                    )
                  })}
                </Item>
              </Grid>
              <Grid xs={12}>
                <Item>
                  <h2 style={{ padding: '1%' }}>Productos</h2>
                  <Divider />
                  <TableContainer>
                    <Table>
                      <TableHead>
                        <TableRow hover>
                          <TableCell>
                            <p className='elemento-producto'>Producto</p>
                          </TableCell>
                          <TableCell>
                            <p className='elemento-producto'>Cantidad</p>
                          </TableCell>
                          <TableCell>
                            <p className='elemento-producto'>Precio unitario</p>
                          </TableCell>
                          <TableCell>
                            <p className='elemento-producto'>Total</p>
                          </TableCell>
                        </TableRow>
                      </TableHead>
                      <TableBody>
                        {productos.map(({ id, imagen, nombre, referencia, cantidad, precio }) => {
                          return (
                            <TableRow key={id} hover>
                              <TableCell>
                                <div className='producto'>
                                  {/* <img src={imagen} alt='imagen' /> */}
                                  <Image style={{ backgroundColor: '#f6f6f6', borderRadius: '5px' }} src={imagen} alt='imagen' width={80} height={80} />
                                  <div style={{ display: 'block', width: '100%' }}>
                                    <p>{nombre}</p>
                                    <p style={{ color: 'gray' }}>SKU: {referencia}</p>
                                  </div>
                                </div>
                              </TableCell>
                              <TableCell>
                                <p>{cantidad}</p>
                              </TableCell>
                              <TableCell>
                                <p>${precio.toLocaleString('es-CO', { minimumFractionDigits: 2 })}</p>
                              </TableCell>
                              <TableCell>
                                <p>${(cantidad * precio).toLocaleString('es-CO', { minimumFractionDigits: 2 })}</p>
                              </TableCell>
                            </TableRow>
                          )
                        })}
                      </TableBody>
                    </Table>
                  </TableContainer>
                  <Grid container sx={{ padding: '1.5%' }}>
                    <Grid xs={12}>
                      <div>
                        <p className='total'>Total del pedido</p>
                        <p style={{ fontSize: '1.4em' }}>${productos.reduce((acc, { cantidad, precio }) => acc + (cantidad * precio), 0).toLocaleString('es-CO', { minimumFractionDigits: 2 })} </p>
                      </div>
                    </Grid>
                  </Grid>
                </Item>
              </Grid>
            </Grid>
          </Box>
        </main>
      </body>
    </>
  )
}

export default Pedido