'use client'

import Navbar from '@/app/components/navbar'
import React from 'react'
import { styled } from '@mui/material/styles';
import './styles.css'
import { Box, Divider } from '@mui/material'
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Unstable_Grid2';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TablePagination from '@mui/material/TablePagination';
import TableSortLabel from '@mui/material/TableSortLabel';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import postobon from '../../../../public/images/postobon.webp'
import Image from 'next/image';

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
  ...theme.typography.body2,
  padding: theme.spacing(1),
  margin: theme.spacing(2),
}));

const cliente = [
  {
    id: 1,
    nombre: 'Carlos',
    apellido: 'Perez',
    telefono: '1234567890',
    direccion: 'Calle 123',
  }
]

const orden = [
  {
    id: 1,
    fecha: '16 de Mayo de 2025',
    vendedor: 'Sarah Paulson',
    estado: 'En proceso',
  }
]

const productos = [
  {
    id: 1,
    imagen: postobon,
    nombre: 'Producto 1',
    referencia: '123456',
    cantidad: 2,
    precio: 100,
  },
  {
    id: 2,
    imagen: postobon,
    nombre: 'Producto 2',
    referencia: '123456',
    cantidad: 3,
    precio: 100,
  },
  {
    id: 2,
    imagen: postobon,
    nombre: 'Producto 2',
    referencia: '123456',
    cantidad: 3,
    precio: 100,
  },
  {
    id: 2,
    imagen: postobon,
    nombre: 'Producto 2',
    referencia: '123456',
    cantidad: 3,
    precio: 100,
  },
  {
    id: 2,
    imagen: postobon,
    nombre: 'Producto 2',
    referencia: '123456',
    cantidad: 3,
    precio: 100,
  }
]

function Pedido() {
  return (
    <>
      <head>
        <title>Pedido</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </head>
      <body>
        <header>
          <Navbar />
        </header>
        <main>
          <Box className='contenedor'>
            <Grid className='elementos' container spacing={1} columns={2}>
              <Grid xs={6} md={1}>
                <Item>
                  <h2>Detalles del cliente</h2>
                  <Divider />
                  {cliente.map(({ id, nombre, apellido, telefono, direccion }) => {
                    return (
                      <div key={id} className='detalles'>
                        <div>
                          <p className='subtitulo'>Nombre</p>
                          <p>{nombre}</p>
                        </div>
                        <div>
                          <p className='subtitulo'>Apellido</p>
                          <p>{apellido}</p>
                        </div>
                        <div>
                          <p className='subtitulo'>Telefono</p>
                          <p>{telefono}</p>
                        </div>
                        <div>
                          <p className='subtitulo'>Direccion</p>
                          <p>{direccion}</p>
                        </div>
                      </div>
                    )
                  })}
                </Item>
              </Grid>
              <Grid xs={6} md={1}>
                <Item>
                  <h2>Detalles del pedido</h2>
                  <Divider />
                  {orden.map(({ id, fecha, vendedor, estado }) => {
                    return (
                      <div key={id} className='detalles'>
                        <div>
                          <p className='subtitulo'>Pedido No.</p>
                          <p>{id}</p>
                        </div>
                        <div>
                          <p className='subtitulo'>Fecha</p>
                          <p>{fecha}</p>
                        </div>
                        <div>
                          <p className='subtitulo'>Vendedor</p>
                          <p>{vendedor}</p>
                        </div>
                        <div>
                          <p className='subtitulo'>Estado</p>
                          <p><b>{estado}</b></p>
                        </div>
                      </div>
                    )
                  })}
                </Item>
              </Grid>
              <Grid xs={12}>
                <Item>
                  <h2>Productos</h2>
                  <Divider />
                  <TableContainer>
                    <Table>
                      <TableHead>
                        <TableRow hover>
                          <TableCell>
                            <TableSortLabel>
                              <p className='elemento-producto'>Producto</p>
                            </TableSortLabel>
                          </TableCell>
                          <TableCell>
                            <TableSortLabel>
                              <p className='elemento-producto'>Cantidad</p>
                            </TableSortLabel>
                          </TableCell>
                          <TableCell>
                            <TableSortLabel>
                              <p className='elemento-producto'>Precio</p>
                            </TableSortLabel>
                          </TableCell>
                          <TableCell>
                            <TableSortLabel>
                              <p className='elemento-producto'>Total</p>
                            </TableSortLabel>
                          </TableCell>
                        </TableRow>
                      </TableHead>
                      <TableBody>
                        {productos.map(({ id, imagen, nombre, referencia, cantidad, precio }) => {
                          return (
                            <TableRow key={id} hover>
                              <TableCell>
                                <div className='producto'>
                                  {/* <img src={imagen} alt='imagen' /> */}
                                  <Image style={{ backgroundColor: '#f6f6f6', borderRadius: '5px' }} src={imagen} alt='imagen' width={80} height={80} />
                                  <div style={{display: 'block', width: '100%'}}>
                                    <p>{nombre}</p>
                                    <p style={{color: 'gray'}}>SKU: {referencia}</p>
                                  </div>
                                </div>
                              </TableCell>
                              <TableCell>
                                <p>{cantidad}</p>
                              </TableCell>
                              <TableCell>
                                <p>{precio}</p>
                              </TableCell>
                              <TableCell>
                                <p>{cantidad * precio}</p>
                              </TableCell>
                            </TableRow>
                          )
                        })}
                      </TableBody>
                    </Table>
                  </TableContainer>
                </Item>
              </Grid>
            </Grid>
          </Box>
        </main>
      </body>
    </>
  )
}

export default Pedido