import { Inter } from "next/font/google";
import "./globals.css"
import  { AppWrapper }  from "./context/index.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "InventoTrack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppWrapper>
        <body className={inter.className}>{children}</body>
      </AppWrapper>
    </html>
  );
}
