import Image from "next/image";
import styles from "./page.module.css";

export default function Home() {
  return (
    <>
    <head>
      <title>InventoTrack</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.ico" />
    </head>
    <body>

    </body>
    </>
  );
}
