"""product image update

Revision ID: 132df222ebcc
Revises: 7a3a68029d4e
Create Date: 2024-05-08 16:23:19.216064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132df222ebcc'
down_revision = '7a3a68029d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
