"""model pedido

Revision ID: 1efaa498393d
Revises: 29db63391f81
Create Date: 2024-05-08 15:56:02.972838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efaa498393d'
down_revision = '29db63391f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('total_pedido', sa.Integer(), nullable=True),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=True),
    sa.Column('cantidad_producto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido')
    # ### end Alembic commands ###
