"""update modelo producto

Revision ID: 29db63391f81
Revises: ac1511f1e4f4
Create Date: 2024-05-05 16:30:06.704316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29db63391f81'
down_revision = 'ac1511f1e4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
