"""update Pedido

Revision ID: 47d474f7acf7
Revises: 132df222ebcc
Create Date: 2024-05-08 19:44:08.060228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d474f7acf7'
down_revision = '132df222ebcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('cantidad_producto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint('pedido_id_producto_fkey', type_='foreignkey')
        batch_op.drop_column('id_producto')
        batch_op.drop_column('cantidad_producto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_producto', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_producto', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('pedido_id_producto_fkey', 'producto', ['id_producto'], ['id'])

    op.drop_table('producto_pedido')
    # ### end Alembic commands ###
