"""models upgrade

Revision ID: 50b981610b0d
Revises: 298fbf6f8ca9
Create Date: 2024-04-24 21:19:12.936953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b981610b0d'
down_revision = '298fbf6f8ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=128), nullable=True))

    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('administrador', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
