"""Update Pedido model. Id vendedor

Revision ID: 9f5dd8088ac4
Revises: fd6a38c22a67
Create Date: 2024-05-19 19:12:19.740241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5dd8088ac4'
down_revision = 'fd6a38c22a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_vendedor', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vendedor', ['id_vendedor'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_vendedor')

    # ### end Alembic commands ###
