"""Creando modelo producto

Revision ID: ac1511f1e4f4
Revises: 9a6dfee26518
Create Date: 2024-05-05 15:58:35.592783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1511f1e4f4'
down_revision = '9a6dfee26518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=128), nullable=True),
    sa.Column('categoria', sa.String(length=128), nullable=True),
    sa.Column('referencia', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('administrador', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("'admin'::character varying"))

    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("'vendedor'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("'vendedor'::character varying"))

    with op.batch_alter_table('administrador', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("'admin'::character varying"))

    op.drop_table('producto')
    # ### end Alembic commands ###
